# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'keyDownViewController' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for keyDownViewController
pod 'HotKey'


  target 'keyDownViewControllerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'keyDownViewControllerUITests' do
    # Pods for testing
  end

end
